### ISSUE TITLE
Export Updates (1/3)- Suitable Areas

### ISSUE THREAD

**Issue by gclapp1** [kartoza/rezoning-2-project#18]
Include suitable areas as vectors in export options

**Comment by timlinux** [comment]
Can we split into three issues as per bullets above please.

**Comment by NEDJIMAbelgacem** [comment]
Hi @gclapp1 & @ClaraIV 
Just a bit of a clarification here: Do you want to add new option in the DOWNLOAD OPTIONS menu to download the suitable areas as a vector layer? If so, I think that's a bit problematic because the suitable areas layer itself is a raster layer not a vector layer.
Would you be happy to add a new option below "score (GeoTIFF)" option, let's call it "suitable areas (GeoTIFF)"?, where the user can download that layer as a GeoTIFF not a vector layer?
![image](https://user-images.githubusercontent.com/29183781/208645399-d85edc92-457d-44a3-88b8-9ac866d0dc66.png)

**Comment by ClaraIV** [comment]
Thank you for the explanations, I thought it was a vector file. It doesn't help to export it as Geotiff, since we already get this twice in the form of the LCOE geotiff and the Score geotiff - it is the same area represented, with diff values with the raster cells. Is it complicated to <polygonize> the resulting areas and provide this option for export?

**Comment by NEDJIMAbelgacem** [comment]
@ClaraIV Sorry I don't understand your question clearly.
Basically from what I see is the score geotiffs (Same goes for LCOE geotiffs export) are exported with 2 bands: 1 for the score value and the other one is the mask for suitable areas (0 for pixels not in the area and 255 for pixels that are in the suitable areas). 
Do you want to know if it is possible to convert the suitable areas rasters to vectors ?

**Comment by ClaraIV** [comment]
yes, exactly. we don't need the suitable areas in geotiff format, it
doesn't bring any value. If its easy to convert to vector, that would be
great, otherwise let us discuss what it would entail, thank you!

**Comment by LunaAsefaw** [comment]
I am able to download vector files for the suitable areas 
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/900f7f3c-01d9-40d2-a0e4-8a38282a438b)

**Comment by LunaAsefaw** [comment]
I see that Cape Verde generates an invalid shapefile for suitable areas and I am not sure how many other countries have this error so I will test each country again to make sure. For now this issue is open

**Comment by gclapp1** [comment]
Any follow-up from testing the suitable areas?

**Comment by LunaAsefaw** [comment]
@gclapp1 The following countries still generate invalid shapefiles for suitable areas: Kazakhstan, Monaco, Nauru, Norfolk Island, Northern Mariana, Pitcairn, Togo, Tonga, Turkemistan, Wallis and Futuna and Guam. We are not yet sure why and are still under review

**Comment by gclapp1** [comment]
@LunaAsefaw Have these countries been addressed yet?

For Kazakhstan: I get stuck on the following message:
![Image](https://github.com/kartoza/rezoning-2-project/assets/57463392/73623141-98ae-4cf7-b1b2-6b9d5cff5565)

Tested the next three countries and found for **All Monaco resources and sizes, Nauru Onshore & Offshore all sizes, All Norfolk Islands resources and sizes:** I receive the yellow caution triangle with no available zones even when all filters are at min and max.

**Comment by LunaAsefaw** [comment]
@gclapp1  Regarding Kazakhstan, it might be due to a large number of suitable areas being generated so it takes extremely long but we will investigate this.

I did not flag Monaco because no suitable areas were returned and when Clara defined the problem she said that it is possible that some countries do not have any suitable areas so if no suitable areas are generated for any grid level then zones are not expected so I did not flag it. Additionally I tried it on the production site but it doesn't generate results either (just says it will take a few moments and runs forever). How do I distinguish between an error or if there are actually no suitable sites in that region?
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/bafc4e7e-f207-4144-a76e-32e350c99bf8)

Nauru passed this ticket because it generates valid shapefiles for zones and suitable areas in QGIS, which is what this ticket is  about so I passed it but the issue of it returning zones and suitable areas but no results for the summary tab was recorded as a different issue and our developer was notified and is working on it
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/3a21c4b1-af94-428b-80f5-ab36bcc2a490)

Regarding Norfolk, it generated results for onshore, solar and offshore but if you did not get results
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/c2f49d6b-c1e8-44cf-9dc4-b6adcf97bff6)
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/63a645e1-bd24-43d8-abad-8ad793f2e623)

Then I ran it again using the same parameters and it generated the error message so this inconsistency needs to be investigated @dimasciput 
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/51be877e-d7f0-430f-846c-671d5ce5f67f)
