### ISSUE TITLE
Use speech icon for feedback

### ISSUE THREAD

**Issue by timlinux** [kartoza/rezoning-2-project#44]
![image](https://user-images.githubusercontent.com/178003/220377034-ba00948b-05cd-4679-9233-54069cf99987.png)

Also @clara asks for a new step in the first open wizard (step 8) that hints to the user to use it to get help / feedback.

![image](https://user-images.githubusercontent.com/178003/220377240-e352c9cd-a5af-41f2-8fa9-aa56cfaada3f.png)

@ClaraIV please provide the specific text to use

Also move the icon to launch the feedback for to the bottom right as implemented by most web sites:

![image](https://user-images.githubusercontent.com/178003/220377867-b01e2488-b3e2-4b85-94c8-0daa6daba6ce.png)

**Comment by NEDJIMAbelgacem** [comment]
I moved the feedback form to the bottom right below the analysis form and it is hidden by default unless you click "Show feedback form":
![feedback-form-position](https://user-images.githubusercontent.com/29183781/225004606-79a7845c-a74d-4e64-b1bd-4d5c66732d26.png)

**Comment by ClaraIV** [comment]
this looks good! can you reduce the size of the font to match the <Zone Analysis>? 
Also, perhaps let's only write <Feedback Form> (not in all caps) and when it is open can we make the <Submit Feedback> box the color blue, similar to the <Generate Zones> button?
Do you think we should add a color to the <Feedback Form> button as well? so that it stands up? or a shadow, similar to the <Export> button?

**Comment by akshay2408** [comment]
PR
<img width="334" alt="Screenshot 2023-04-05 at 2 23 35 PM" src="https://user-images.githubusercontent.com/11027786/230031934-e65ee52f-91a1-424e-9bc7-8e7741fc8bd7.png">
 -  https://github.com/worldbank/WB-rezoning-explorer/pull/15
