### ISSUE TITLE
update existing filters with csv file data

### ISSUE THREAD

**Issue by akshay2408** [kartoza/rezoning-2-project#52]
This is subtask 2 of #50

**Comment by ClaraIV** [comment]
This works for Spatial and Weights, but not for the Economic Parameters;
I modified a value in the Economic Parameters tab and the export converted the value to "string", marking it as "5" instead of 5 - see below. Upon import, the corresponding field remained blank and did not populate.
Please test if yourself, modify values in the Economic tab, export csv, reset tab and re-import csv. @akshay2408 


![Image](https://user-images.githubusercontent.com/9391517/234328313-a6af4107-3761-4ef0-88fe-d80b790063e2.png)



![Image](https://user-images.githubusercontent.com/9391517/234328430-f8e3b493-4216-484a-beda-19d24a2d1ba7.png)

**Comment by LunaAsefaw** [comment]
@dimasciput I think the issue still persists. I changed a parameter ('Unavailability factor') to string and then imported it and the parameter online was empty 

![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/ca9a5876-a910-4529-95bd-011dc4aa3bc6)
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/eb04085e-871d-47ee-9436-b4e413ee4bba)
