### ISSUE TITLE
missing countries

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/rezoning-2-project#63]
The first issue we ever discussed was adding the missing countries to the platform. I just searched for the US and Russia and they are missing - can you please provide an update on this?
This is part of the TOR and was the starting point of the entire effort.

**Comment by NEDJIMAbelgacem** [comment]
The missing countries have been added back.
It was a merge problem and the countries were disabled by accident..

**Comment by ClaraIV** [comment]
please re-name to "Satellite Basemap"

**Comment by ClaraIV** [comment]
@NEDJIMAbelgacem there is strange behavior with some of the newly added countries.
For example, with Fiji -> I had to do the country selection several times for my selection to stick; I was getting the screen below, as I do for Kiribati, after country and resource selection; the country selection doesnt stay on

Please test this internally for the following countries before submitting - I am turning it back for revision; please try running the tool when testing, not only searching the country catalog.

Fiji
Kiribati
Marshall Islands
Niue
Tuvalu

![image](https://user-images.githubusercontent.com/9391517/233371732-07542dff-8561-4a0f-b878-4b2273879acb.png)

**Comment by dimasciput** [comment]
@akshay2408 can you address this ticket? Or do you need my help?

**Comment by dimasciput** [comment]
@akshay2408 it seems that the error is with the api : /v1/filter/KIR/solar/layers. I got 500 error code.

**Comment by LunaAsefaw** [comment]
Countries are still missing so I have moved this to 'to-do', I will upload the list of missing countries soon

**Comment by ClaraIV** [comment]
Thank you very much @LunaAsefaw for the list.
Let us please focus on adding the following countries for this version of the app - some of them (disputed territories) might need to undergo clearance from our Cartography Unit.

Côte d'Ivoire
Kosovo
Kyrgyzstan
São Tomé and Príncipe

**Comment by LunaAsefaw** [comment]
Thank you @ClaraIV 
Perfect, @akshay2408 please note the comment above

**Comment by ClaraIV** [comment]
hi @LunaAsefaw , I was testing some of the newly added countries, just ran the below analysis for Fiji and I get conflicting results, please see + no error message:

![image](https://github.com/kartoza/rezoning-2-project/assets/9391517/fc064f31-f445-4ce3-a1f2-35cf5fcd68d4)

**Comment by LunaAsefaw** [comment]
Tuvalu and Tokelau are on the system but their geometry is missing @dimasciput

**Comment by gclapp1** [comment]
The four countries we discussed (i) Côte d'Ivoire, (ii) Kosovo, (ii) Kyrgyzstan, (iv) São Tomé and Príncipe all work.

The three countries mentioned in Luna's comment above (Tuvalu, Tokelau and United States Minor Outlying Islands) still do not have available data.

We had discussed using Administrative Boundaries for the U.S but I don't see that as an option though the 25KM and 50 KM zone generation seems to work, it just takes awhile. 

Can discuss those as separate issues and closing ticket.

**Comment by LunaAsefaw** [comment]
Hi @ClaraIV sorry I just saw this comment now. We were making changes to Fiji last week so that error probably happened because changes were happening in the backend.

@gclapp1 I raised that concern with Dimas, I saw that the countries that intersect the antimerdian showed no data for onshore and solar (Kiribati and Fiji for example) but returned data for offshore. I wanted to test this on the production site to assess if there is an issue with these countries or there really are no suitable areas but they're not on the staging site.

As for Tuvalu, Tokelau and United States Minor Outlying Islands, this issue relates to #27 and #42, where we touch on the fact that these countries exist on the site but their geometry file seem to be missing. So these are being looked at.

Lastly, we were thinking of keeping just the administrative countries but since Dimas got the site to generate zones without crashing the site, we thought we could include the function for anyone hoping to analyze on a grid level. Regarding the boundary analyses, you are right and Dimas was made aware of this issue and is debugging it.

![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/97bd59c5-bc4f-4860-95be-08a6065ccc36)

as seen above @dimasciput, since US topo.json was done on a country level after the merged states, the adminstrative boundaries analysis does not work. Cayman Islands is a similar situation, it returns one big zone because it treats the whole country as one boundary, instead of adminstrative boundaries.

![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/80e1f379-7944-4406-a35f-a707a620a82d)
