### ISSUE TITLE
Fix min/max range for regions, specifically Caspian sea

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/rezoning-2-project#80]
🐛 Describe the bug

The minimum and maximum of the parameters differ for the regions between the staging and production site. This bug only occurs for regions and not countries.

💡 Expected behavior

The default minimum and maximum values for the parameters for the staging and production site should be the same.

📸 Screenshot
Min/Max on the staging site
![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/bcbe4c4d-722c-41ed-91e5-b40597d8d0da)

Min/Max on the production site
![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/552cffae-9070-4966-99f7-423046f1b155)

**Comment by dimasciput** [comment]
Hi @LunaAsefaw 

This is because Caspian has not been properly clipped in the production.

Production : 
![image](https://github.com/kartoza/rezoning-2-project/assets/1979569/040fcd78-b70b-46b4-b823-fe823e39479b)

Staging :
![image](https://github.com/kartoza/rezoning-2-project/assets/1979569/d21c57c6-662c-4c59-bc8f-b319538506b4)

**Comment by LunaAsefaw** [comment]
And I'm assuming the clipping also then affects the range of default values? @dimasciput

**Comment by dimasciput** [comment]
@LunaAsefaw yes that's correct

**Comment by gclapp1** [comment]
Related to #40 and closing accordingly, thanks!
